name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  quality-checks:
    name: Quality Assurance
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Sort Imports
        run: ./scripts/sort_imports.sh

      - name: Run KtLint (Code Style)
        run: ./gradlew --no-daemon ktlintCheck

      - name: Run Detekt (Static Analysis)
        run: ./gradlew --no-daemon detekt

      - name: Run Android Lint
        run: ./gradlew --no-daemon lint

      - name: Upload QA Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qa-reports
          path: |
            app/build/reports/detekt/
            app/build/reports/ktlint/
            app/build/reports/lint-results/
          retention-days: 30

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Gradle caching
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew --no-daemon test

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Build Release APK
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/debug/**/*.apk
          retention-days: 30

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: release-apks
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/release/**/*.apk
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/reports/tests/
          retention-days: 30

